"""Phase 1 task: run schema validation across everything downloaded so far
and write a human-readable quirks report to docs/data_quirks.md.

Two deliberately different layers:
  - f1qp.data.schema.validate_laps applies a loose, fixed sanity ceiling
    per session type at DOWNLOAD time (one session, no dataset to compare
    against yet) - it only catches something obviously dead.
  - This script runs AFTER a full download batch, when the whole dataset's
    distribution is available, and flags genuine statistical outliers per
    session type - Tukey's rule, flag past Q3 + 1.5*IQR - instead of
    another guessed number. A fixed "Q should be under 35%" bar flagged
    ~40 completely normal qualifying sessions on real data (every push lap
    brackets an out-lap and an in-lap, so 35-43% null is just what Q looks
    like); the data itself should set the bar, not another guess.

Run after download_2026.py / download_historical.py have produced at
least some files:
    python scripts/validate_schema.py
"""
from __future__ import annotations

from pathlib import Path

import pandas as pd

from f1qp.data.schema import REQUIRED_LAP_COLUMNS

DATA_DIR = Path(__file__).resolve().parents[1] / "data" / "raw"
REPORT_PATH = Path(__file__).resolve().parents[1] / "docs" / "data_quirks.md"

# A floor under the Tukey bound: never flag below this even if a session
# type's own IQR comes out tighter than this (e.g. too few samples yet, or
# a session type that's naturally very consistent) - a backstop, not the
# real bar. The real bar is whatever the dataset's own distribution says.
MIN_FLAG_THRESHOLD = 0.45


def _collect_sessions() -> pd.DataFrame:
    """One row per (file, session_code): missing columns + null LapTime %."""
    files = sorted(DATA_DIR.rglob("*.parquet"))
    rows = []
    for f in files:
        df = pd.read_parquet(f)
        if "SessionCode" not in df.columns:
            rows.append({"file": f, "session_code": None, "missing": REQUIRED_LAP_COLUMNS, "null_pct": None})
            continue
        for session_code, sdf in df.groupby("SessionCode"):
            missing = [c for c in REQUIRED_LAP_COLUMNS if c not in sdf.columns]
            null_pct = float(sdf["LapTime"].isna().mean()) if "LapTime" in sdf.columns and len(sdf) else None
            rows.append({"file": f, "session_code": session_code, "missing": missing, "null_pct": null_pct})
    return pd.DataFrame(rows)


def outlier_bounds(sessions: pd.DataFrame) -> dict:
    """Tukey's rule per session type: Q3 + 1.5*IQR, floored at MIN_FLAG_THRESHOLD."""
    bounds = {}
    valid = sessions.dropna(subset=["null_pct"])
    for session_code, grp in valid.groupby("session_code"):
        q1, q3 = grp["null_pct"].quantile([0.25, 0.75])
        bound = q3 + 1.5 * (q3 - q1)
        bounds[session_code] = max(float(bound), MIN_FLAG_THRESHOLD)
    return bounds


def main() -> None:
    sessions = _collect_sessions()
    bounds = outlier_bounds(sessions)

    lines = [
        "# Data Quirks & Assumptions",
        "",
        "_Auto-generated by scripts/validate_schema.py - re-run after every download batch._",
        "",
        "A meaningful share of laps in every session legitimately have no "
        "`LapTime` - out-laps, in-laps, and laps cut short by a red flag or "
        "safety car never complete a timed lap. Rather than a fixed bar, "
        "each session type's normal range is computed from this dataset "
        "(Tukey's rule: flag past Q3 + 1.5×IQR) and only genuine "
        "outliers are listed below.",
        "",
        f"Checked {sessions['file'].nunique()} round files, {len(sessions)} sessions total.",
        "",
        "Normal-range ceiling used per session type (recomputed from this run):",
    ]
    for session_code, bound in sorted(bounds.items()):
        lines.append(f"- {session_code}: flagged past {bound:.1%}")
    lines.append("")

    flagged = 0
    for _, row in sessions.iterrows():
        is_missing = bool(row["missing"])
        is_no_session_col = row["session_code"] is None
        is_outlier = (
            row["null_pct"] is not None
            and row["session_code"] in bounds
            and row["null_pct"] > bounds[row["session_code"]]
        )
        if is_missing or is_no_session_col or is_outlier:
            flagged += 1
            pct_str = f"{row['null_pct']:.1%}" if row["null_pct"] is not None else "n/a"
            lines.append(
                f"- **{row['file'].relative_to(DATA_DIR)}** [{row['session_code']}] - "
                f"missing columns: {row['missing'] or 'none'}, null LapTime: {pct_str}"
            )

    if flagged == 0:
        lines.append("No sessions outside their session type's normal range.")

    REPORT_PATH.parent.mkdir(parents=True, exist_ok=True)
    REPORT_PATH.write_text("\n".join(lines) + "\n")
    print(f"Wrote {REPORT_PATH} - {flagged}/{len(sessions)} sessions flagged across {sessions['file'].nunique()} files.")


if __name__ == "__main__":
    main()
